### ISSUE TITLE
Is this safe to use elsewhere?

### ISSUE THREAD

**Issue by harrysolovay** [denoland/automation#20]
I haven't found a great release workflow for my Deno projects. I'm wondering if `denoland/automation` is safe to use, or if it's intended only for the Denoland org's uses? Any recommendations regarding releases would be greatly appreciated!

**Comment by dsherret** [comment]
It's tailored for Denoland's Rust repos. It's not really suited for Deno projects and I wouldn't recommend depending on it because it's really unstable (though fine to do if you really want to 🙂).

**Comment by harrysolovay** [comment]
Thanks for the quick reply! Are there any CI version-bumping/changelog-gen/pr tools that you'd recommend for Deno projects?

**Comment by dsherret** [comment]
It really depends. If you're publishing to deno.land/x which works off git tags, then you can just use GitHub releases (which has the ability to auto-generate a changelog) and publish a release tagged with the new version.

**Comment by harrysolovay** [comment]
Gotcha. I don't want to impose (so please feel free to just close this issue & ignore :), but the path forward is still somewhat ambiguous.

For version bumping, would you recommend a manually-triggered GH workflow like [what you have in `std`](https://github.com/denoland/deno_std/blob/main/.github/workflows/version_bump.yml#L4)? And would that mean implementing the version bumping manually, as you have [in `std`](https://github.com/denoland/deno_std/blob/main/_tools/release/01_bump_version.ts). I see this script also regenerates an elegant `Releases.md` file! I like that! The [create PR flow](https://github.com/denoland/deno_std/blob/main/_tools/release/02_create_pr.ts) is also extremely nice! You do the tagging in CI. All around, your approach is exactly what I'd like for my own repos. But it does seem like an undertaking to maintain / tackle edge cases. Any tips to simplify?

**Comment by dsherret** [comment]
I'm not sure why we store the version in deno_std/version.ts and it seems still overly complicated to me. I would recommend not storing a version or release notes in the repo. That way you don't have to create a PR to do a release and instead you just publish a GitHub release which will auto-generate your release notes as well. For a changelog, you can provide people with the GitHub release page and that would also give you a single source of truth on the release notes.

**Comment by harrysolovay** [comment]
This is great advice (which I shall follow)! Thank you @dsherret –– as always, you're of much help!

**Comment by harrysolovay** [comment]
One more question: do you have any advice on how you would approach retrieving the version within the package? A common use case is to inform a CLI's version command.

```
my-cli --version
```

The approach you described does not entail storing the version in the repo. This makes it inaccessible to the code. Ideally, there's a way to retrieve the version without complicating the approach you described above.
